# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cartographer/common/proto/ceres_solver_options.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cartographer/common/proto/ceres_solver_options.proto',
  package='cartographer.common.proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n4cartographer/common/proto/ceres_solver_options.proto\x12\x19\x63\x61rtographer.common.proto\"e\n\x12\x43\x65resSolverOptions\x12\x1e\n\x16use_nonmonotonic_steps\x18\x01 \x01(\x08\x12\x1a\n\x12max_num_iterations\x18\x02 \x01(\x05\x12\x13\n\x0bnum_threads\x18\x03 \x01(\x05\x62\x06proto3'
)




_CERESSOLVEROPTIONS = _descriptor.Descriptor(
  name='CeresSolverOptions',
  full_name='cartographer.common.proto.CeresSolverOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='use_nonmonotonic_steps', full_name='cartographer.common.proto.CeresSolverOptions.use_nonmonotonic_steps', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max_num_iterations', full_name='cartographer.common.proto.CeresSolverOptions.max_num_iterations', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_threads', full_name='cartographer.common.proto.CeresSolverOptions.num_threads', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=184,
)

DESCRIPTOR.message_types_by_name['CeresSolverOptions'] = _CERESSOLVEROPTIONS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CeresSolverOptions = _reflection.GeneratedProtocolMessageType('CeresSolverOptions', (_message.Message,), {
  'DESCRIPTOR' : _CERESSOLVEROPTIONS,
  '__module__' : 'cartographer.common.proto.ceres_solver_options_pb2'
  # @@protoc_insertion_point(class_scope:cartographer.common.proto.CeresSolverOptions)
  })
_sym_db.RegisterMessage(CeresSolverOptions)


# @@protoc_insertion_point(module_scope)
