# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cartographer/mapping/proto/cell_limits_2d.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cartographer/mapping/proto/cell_limits_2d.proto',
  package='cartographer.mapping.proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n/cartographer/mapping/proto/cell_limits_2d.proto\x12\x1a\x63\x61rtographer.mapping.proto\"6\n\nCellLimits\x12\x13\n\x0bnum_x_cells\x18\x01 \x01(\x05\x12\x13\n\x0bnum_y_cells\x18\x02 \x01(\x05\x62\x06proto3'
)




_CELLLIMITS = _descriptor.Descriptor(
  name='CellLimits',
  full_name='cartographer.mapping.proto.CellLimits',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='num_x_cells', full_name='cartographer.mapping.proto.CellLimits.num_x_cells', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_y_cells', full_name='cartographer.mapping.proto.CellLimits.num_y_cells', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=133,
)

DESCRIPTOR.message_types_by_name['CellLimits'] = _CELLLIMITS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CellLimits = _reflection.GeneratedProtocolMessageType('CellLimits', (_message.Message,), {
  'DESCRIPTOR' : _CELLLIMITS,
  '__module__' : 'cartographer.mapping.proto.cell_limits_2d_pb2'
  # @@protoc_insertion_point(class_scope:cartographer.mapping.proto.CellLimits)
  })
_sym_db.RegisterMessage(CellLimits)


# @@protoc_insertion_point(module_scope)
