# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cartographer/mapping/proto/connected_components.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cartographer/mapping/proto/connected_components.proto',
  package='cartographer.mapping.proto',
  syntax='proto3',
  serialized_options=b'B\035ConnectedComponentsOuterClass',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n5cartographer/mapping/proto/connected_components.proto\x12\x1a\x63\x61rtographer.mapping.proto\"\xa3\x01\n\x13\x43onnectedComponents\x12_\n\x13\x63onnected_component\x18\x01 \x03(\x0b\x32\x42.cartographer.mapping.proto.ConnectedComponents.ConnectedComponent\x1a+\n\x12\x43onnectedComponent\x12\x15\n\rtrajectory_id\x18\x01 \x03(\x05\x42\x1f\x42\x1d\x43onnectedComponentsOuterClassb\x06proto3'
)




_CONNECTEDCOMPONENTS_CONNECTEDCOMPONENT = _descriptor.Descriptor(
  name='ConnectedComponent',
  full_name='cartographer.mapping.proto.ConnectedComponents.ConnectedComponent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='trajectory_id', full_name='cartographer.mapping.proto.ConnectedComponents.ConnectedComponent.trajectory_id', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=206,
  serialized_end=249,
)

_CONNECTEDCOMPONENTS = _descriptor.Descriptor(
  name='ConnectedComponents',
  full_name='cartographer.mapping.proto.ConnectedComponents',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='connected_component', full_name='cartographer.mapping.proto.ConnectedComponents.connected_component', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_CONNECTEDCOMPONENTS_CONNECTEDCOMPONENT, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=249,
)

_CONNECTEDCOMPONENTS_CONNECTEDCOMPONENT.containing_type = _CONNECTEDCOMPONENTS
_CONNECTEDCOMPONENTS.fields_by_name['connected_component'].message_type = _CONNECTEDCOMPONENTS_CONNECTEDCOMPONENT
DESCRIPTOR.message_types_by_name['ConnectedComponents'] = _CONNECTEDCOMPONENTS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ConnectedComponents = _reflection.GeneratedProtocolMessageType('ConnectedComponents', (_message.Message,), {

  'ConnectedComponent' : _reflection.GeneratedProtocolMessageType('ConnectedComponent', (_message.Message,), {
    'DESCRIPTOR' : _CONNECTEDCOMPONENTS_CONNECTEDCOMPONENT,
    '__module__' : 'cartographer.mapping.proto.connected_components_pb2'
    # @@protoc_insertion_point(class_scope:cartographer.mapping.proto.ConnectedComponents.ConnectedComponent)
    })
  ,
  'DESCRIPTOR' : _CONNECTEDCOMPONENTS,
  '__module__' : 'cartographer.mapping.proto.connected_components_pb2'
  # @@protoc_insertion_point(class_scope:cartographer.mapping.proto.ConnectedComponents)
  })
_sym_db.RegisterMessage(ConnectedComponents)
_sym_db.RegisterMessage(ConnectedComponents.ConnectedComponent)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
