# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cartographer/mapping/proto/grid_2d.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cartographer.mapping.proto import map_limits_pb2 as cartographer_dot_mapping_dot_proto_dot_map__limits__pb2
from cartographer.mapping.proto import probability_grid_pb2 as cartographer_dot_mapping_dot_proto_dot_probability__grid__pb2
from cartographer.mapping.proto import tsdf_2d_pb2 as cartographer_dot_mapping_dot_proto_dot_tsdf__2d__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='cartographer/mapping/proto/grid_2d.proto',
  package='cartographer.mapping.proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n(cartographer/mapping/proto/grid_2d.proto\x12\x1a\x63\x61rtographer.mapping.proto\x1a+cartographer/mapping/proto/map_limits.proto\x1a\x31\x63\x61rtographer/mapping/proto/probability_grid.proto\x1a(cartographer/mapping/proto/tsdf_2d.proto\"\xa7\x03\n\x06Grid2D\x12\x35\n\x06limits\x18\x01 \x01(\x0b\x32%.cartographer.mapping.proto.MapLimits\x12\r\n\x05\x63\x65lls\x18\x02 \x03(\x05\x12\x43\n\x0fknown_cells_box\x18\x03 \x01(\x0b\x32*.cartographer.mapping.proto.Grid2D.CellBox\x12J\n\x13probability_grid_2d\x18\x04 \x01(\x0b\x32+.cartographer.mapping.proto.ProbabilityGridH\x00\x12\x35\n\x07tsdf_2d\x18\x05 \x01(\x0b\x32\".cartographer.mapping.proto.TSDF2DH\x00\x12\x1f\n\x17min_correspondence_cost\x18\x06 \x01(\x02\x12\x1f\n\x17max_correspondence_cost\x18\x07 \x01(\x02\x1a\x45\n\x07\x43\x65llBox\x12\r\n\x05max_x\x18\x01 \x01(\x05\x12\r\n\x05max_y\x18\x02 \x01(\x05\x12\r\n\x05min_x\x18\x03 \x01(\x05\x12\r\n\x05min_y\x18\x04 \x01(\x05\x42\x06\n\x04gridb\x06proto3'
  ,
  dependencies=[cartographer_dot_mapping_dot_proto_dot_map__limits__pb2.DESCRIPTOR,cartographer_dot_mapping_dot_proto_dot_probability__grid__pb2.DESCRIPTOR,cartographer_dot_mapping_dot_proto_dot_tsdf__2d__pb2.DESCRIPTOR,])




_GRID2D_CELLBOX = _descriptor.Descriptor(
  name='CellBox',
  full_name='cartographer.mapping.proto.Grid2D.CellBox',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='max_x', full_name='cartographer.mapping.proto.Grid2D.CellBox.max_x', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max_y', full_name='cartographer.mapping.proto.Grid2D.CellBox.max_y', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='min_x', full_name='cartographer.mapping.proto.Grid2D.CellBox.min_x', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='min_y', full_name='cartographer.mapping.proto.Grid2D.CellBox.min_y', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=557,
  serialized_end=626,
)

_GRID2D = _descriptor.Descriptor(
  name='Grid2D',
  full_name='cartographer.mapping.proto.Grid2D',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='limits', full_name='cartographer.mapping.proto.Grid2D.limits', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cells', full_name='cartographer.mapping.proto.Grid2D.cells', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='known_cells_box', full_name='cartographer.mapping.proto.Grid2D.known_cells_box', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='probability_grid_2d', full_name='cartographer.mapping.proto.Grid2D.probability_grid_2d', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tsdf_2d', full_name='cartographer.mapping.proto.Grid2D.tsdf_2d', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='min_correspondence_cost', full_name='cartographer.mapping.proto.Grid2D.min_correspondence_cost', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max_correspondence_cost', full_name='cartographer.mapping.proto.Grid2D.max_correspondence_cost', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_GRID2D_CELLBOX, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='grid', full_name='cartographer.mapping.proto.Grid2D.grid',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=211,
  serialized_end=634,
)

_GRID2D_CELLBOX.containing_type = _GRID2D
_GRID2D.fields_by_name['limits'].message_type = cartographer_dot_mapping_dot_proto_dot_map__limits__pb2._MAPLIMITS
_GRID2D.fields_by_name['known_cells_box'].message_type = _GRID2D_CELLBOX
_GRID2D.fields_by_name['probability_grid_2d'].message_type = cartographer_dot_mapping_dot_proto_dot_probability__grid__pb2._PROBABILITYGRID
_GRID2D.fields_by_name['tsdf_2d'].message_type = cartographer_dot_mapping_dot_proto_dot_tsdf__2d__pb2._TSDF2D
_GRID2D.oneofs_by_name['grid'].fields.append(
  _GRID2D.fields_by_name['probability_grid_2d'])
_GRID2D.fields_by_name['probability_grid_2d'].containing_oneof = _GRID2D.oneofs_by_name['grid']
_GRID2D.oneofs_by_name['grid'].fields.append(
  _GRID2D.fields_by_name['tsdf_2d'])
_GRID2D.fields_by_name['tsdf_2d'].containing_oneof = _GRID2D.oneofs_by_name['grid']
DESCRIPTOR.message_types_by_name['Grid2D'] = _GRID2D
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Grid2D = _reflection.GeneratedProtocolMessageType('Grid2D', (_message.Message,), {

  'CellBox' : _reflection.GeneratedProtocolMessageType('CellBox', (_message.Message,), {
    'DESCRIPTOR' : _GRID2D_CELLBOX,
    '__module__' : 'cartographer.mapping.proto.grid_2d_pb2'
    # @@protoc_insertion_point(class_scope:cartographer.mapping.proto.Grid2D.CellBox)
    })
  ,
  'DESCRIPTOR' : _GRID2D,
  '__module__' : 'cartographer.mapping.proto.grid_2d_pb2'
  # @@protoc_insertion_point(class_scope:cartographer.mapping.proto.Grid2D)
  })
_sym_db.RegisterMessage(Grid2D)
_sym_db.RegisterMessage(Grid2D.CellBox)


# @@protoc_insertion_point(module_scope)
