# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cartographer/mapping/proto/hybrid_grid.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cartographer/mapping/proto/hybrid_grid.proto',
  package='cartographer.mapping.proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n,cartographer/mapping/proto/hybrid_grid.proto\x12\x1a\x63\x61rtographer.mapping.proto\"i\n\nHybridGrid\x12\x12\n\nresolution\x18\x01 \x01(\x02\x12\x11\n\tx_indices\x18\x03 \x03(\x11\x12\x11\n\ty_indices\x18\x04 \x03(\x11\x12\x11\n\tz_indices\x18\x05 \x03(\x11\x12\x0e\n\x06values\x18\x06 \x03(\x05\x62\x06proto3'
)




_HYBRIDGRID = _descriptor.Descriptor(
  name='HybridGrid',
  full_name='cartographer.mapping.proto.HybridGrid',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='resolution', full_name='cartographer.mapping.proto.HybridGrid.resolution', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='x_indices', full_name='cartographer.mapping.proto.HybridGrid.x_indices', index=1,
      number=3, type=17, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y_indices', full_name='cartographer.mapping.proto.HybridGrid.y_indices', index=2,
      number=4, type=17, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='z_indices', full_name='cartographer.mapping.proto.HybridGrid.z_indices', index=3,
      number=5, type=17, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='values', full_name='cartographer.mapping.proto.HybridGrid.values', index=4,
      number=6, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=181,
)

DESCRIPTOR.message_types_by_name['HybridGrid'] = _HYBRIDGRID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HybridGrid = _reflection.GeneratedProtocolMessageType('HybridGrid', (_message.Message,), {
  'DESCRIPTOR' : _HYBRIDGRID,
  '__module__' : 'cartographer.mapping.proto.hybrid_grid_pb2'
  # @@protoc_insertion_point(class_scope:cartographer.mapping.proto.HybridGrid)
  })
_sym_db.RegisterMessage(HybridGrid)


# @@protoc_insertion_point(module_scope)
