# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cartographer/mapping/proto/map_limits.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cartographer.mapping.proto import cell_limits_2d_pb2 as cartographer_dot_mapping_dot_proto_dot_cell__limits__2d__pb2
from cartographer.transform.proto import transform_pb2 as cartographer_dot_transform_dot_proto_dot_transform__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='cartographer/mapping/proto/map_limits.proto',
  package='cartographer.mapping.proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n+cartographer/mapping/proto/map_limits.proto\x12\x1a\x63\x61rtographer.mapping.proto\x1a/cartographer/mapping/proto/cell_limits_2d.proto\x1a,cartographer/transform/proto/transform.proto\"\x91\x01\n\tMapLimits\x12\x12\n\nresolution\x18\x01 \x01(\x01\x12\x33\n\x03max\x18\x02 \x01(\x0b\x32&.cartographer.transform.proto.Vector2d\x12;\n\x0b\x63\x65ll_limits\x18\x03 \x01(\x0b\x32&.cartographer.mapping.proto.CellLimitsb\x06proto3'
  ,
  dependencies=[cartographer_dot_mapping_dot_proto_dot_cell__limits__2d__pb2.DESCRIPTOR,cartographer_dot_transform_dot_proto_dot_transform__pb2.DESCRIPTOR,])




_MAPLIMITS = _descriptor.Descriptor(
  name='MapLimits',
  full_name='cartographer.mapping.proto.MapLimits',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='resolution', full_name='cartographer.mapping.proto.MapLimits.resolution', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max', full_name='cartographer.mapping.proto.MapLimits.max', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cell_limits', full_name='cartographer.mapping.proto.MapLimits.cell_limits', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=171,
  serialized_end=316,
)

_MAPLIMITS.fields_by_name['max'].message_type = cartographer_dot_transform_dot_proto_dot_transform__pb2._VECTOR2D
_MAPLIMITS.fields_by_name['cell_limits'].message_type = cartographer_dot_mapping_dot_proto_dot_cell__limits__2d__pb2._CELLLIMITS
DESCRIPTOR.message_types_by_name['MapLimits'] = _MAPLIMITS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MapLimits = _reflection.GeneratedProtocolMessageType('MapLimits', (_message.Message,), {
  'DESCRIPTOR' : _MAPLIMITS,
  '__module__' : 'cartographer.mapping.proto.map_limits_pb2'
  # @@protoc_insertion_point(class_scope:cartographer.mapping.proto.MapLimits)
  })
_sym_db.RegisterMessage(MapLimits)


# @@protoc_insertion_point(module_scope)
