# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cartographer/mapping/proto/map_builder_options.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cartographer.mapping.proto import pose_graph_options_pb2 as cartographer_dot_mapping_dot_proto_dot_pose__graph__options__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='cartographer/mapping/proto/map_builder_options.proto',
  package='cartographer.mapping.proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n4cartographer/mapping/proto/map_builder_options.proto\x12\x1a\x63\x61rtographer.mapping.proto\x1a\x33\x63\x61rtographer/mapping/proto/pose_graph_options.proto\"\xe2\x01\n\x11MapBuilderOptions\x12!\n\x19use_trajectory_builder_2d\x18\x01 \x01(\x08\x12!\n\x19use_trajectory_builder_3d\x18\x02 \x01(\x08\x12\x1e\n\x16num_background_threads\x18\x03 \x01(\x05\x12H\n\x12pose_graph_options\x18\x04 \x01(\x0b\x32,.cartographer.mapping.proto.PoseGraphOptions\x12\x1d\n\x15\x63ollate_by_trajectory\x18\x05 \x01(\x08\x62\x06proto3'
  ,
  dependencies=[cartographer_dot_mapping_dot_proto_dot_pose__graph__options__pb2.DESCRIPTOR,])




_MAPBUILDEROPTIONS = _descriptor.Descriptor(
  name='MapBuilderOptions',
  full_name='cartographer.mapping.proto.MapBuilderOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='use_trajectory_builder_2d', full_name='cartographer.mapping.proto.MapBuilderOptions.use_trajectory_builder_2d', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='use_trajectory_builder_3d', full_name='cartographer.mapping.proto.MapBuilderOptions.use_trajectory_builder_3d', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_background_threads', full_name='cartographer.mapping.proto.MapBuilderOptions.num_background_threads', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pose_graph_options', full_name='cartographer.mapping.proto.MapBuilderOptions.pose_graph_options', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='collate_by_trajectory', full_name='cartographer.mapping.proto.MapBuilderOptions.collate_by_trajectory', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=138,
  serialized_end=364,
)

_MAPBUILDEROPTIONS.fields_by_name['pose_graph_options'].message_type = cartographer_dot_mapping_dot_proto_dot_pose__graph__options__pb2._POSEGRAPHOPTIONS
DESCRIPTOR.message_types_by_name['MapBuilderOptions'] = _MAPBUILDEROPTIONS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MapBuilderOptions = _reflection.GeneratedProtocolMessageType('MapBuilderOptions', (_message.Message,), {
  'DESCRIPTOR' : _MAPBUILDEROPTIONS,
  '__module__' : 'cartographer.mapping.proto.map_builder_options_pb2'
  # @@protoc_insertion_point(class_scope:cartographer.mapping.proto.MapBuilderOptions)
  })
_sym_db.RegisterMessage(MapBuilderOptions)


# @@protoc_insertion_point(module_scope)
