# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cartographer/mapping/proto/motion_filter_options.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cartographer/mapping/proto/motion_filter_options.proto',
  package='cartographer.mapping.proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n6cartographer/mapping/proto/motion_filter_options.proto\x12\x1a\x63\x61rtographer.mapping.proto\"g\n\x13MotionFilterOptions\x12\x18\n\x10max_time_seconds\x18\x01 \x01(\x01\x12\x1b\n\x13max_distance_meters\x18\x02 \x01(\x01\x12\x19\n\x11max_angle_radians\x18\x03 \x01(\x01\x62\x06proto3'
)




_MOTIONFILTEROPTIONS = _descriptor.Descriptor(
  name='MotionFilterOptions',
  full_name='cartographer.mapping.proto.MotionFilterOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='max_time_seconds', full_name='cartographer.mapping.proto.MotionFilterOptions.max_time_seconds', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max_distance_meters', full_name='cartographer.mapping.proto.MotionFilterOptions.max_distance_meters', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max_angle_radians', full_name='cartographer.mapping.proto.MotionFilterOptions.max_angle_radians', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=189,
)

DESCRIPTOR.message_types_by_name['MotionFilterOptions'] = _MOTIONFILTEROPTIONS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MotionFilterOptions = _reflection.GeneratedProtocolMessageType('MotionFilterOptions', (_message.Message,), {
  'DESCRIPTOR' : _MOTIONFILTEROPTIONS,
  '__module__' : 'cartographer.mapping.proto.motion_filter_options_pb2'
  # @@protoc_insertion_point(class_scope:cartographer.mapping.proto.MotionFilterOptions)
  })
_sym_db.RegisterMessage(MotionFilterOptions)


# @@protoc_insertion_point(module_scope)
