# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cartographer/mapping/proto/normal_estimation_options_2d.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cartographer/mapping/proto/normal_estimation_options_2d.proto',
  package='cartographer.mapping.proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n=cartographer/mapping/proto/normal_estimation_options_2d.proto\x12\x1a\x63\x61rtographer.mapping.proto\"N\n\x19NormalEstimationOptions2D\x12\x1a\n\x12num_normal_samples\x18\x01 \x01(\x05\x12\x15\n\rsample_radius\x18\x02 \x01(\x02\x62\x06proto3'
)




_NORMALESTIMATIONOPTIONS2D = _descriptor.Descriptor(
  name='NormalEstimationOptions2D',
  full_name='cartographer.mapping.proto.NormalEstimationOptions2D',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='num_normal_samples', full_name='cartographer.mapping.proto.NormalEstimationOptions2D.num_normal_samples', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sample_radius', full_name='cartographer.mapping.proto.NormalEstimationOptions2D.sample_radius', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=171,
)

DESCRIPTOR.message_types_by_name['NormalEstimationOptions2D'] = _NORMALESTIMATIONOPTIONS2D
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NormalEstimationOptions2D = _reflection.GeneratedProtocolMessageType('NormalEstimationOptions2D', (_message.Message,), {
  'DESCRIPTOR' : _NORMALESTIMATIONOPTIONS2D,
  '__module__' : 'cartographer.mapping.proto.normal_estimation_options_2d_pb2'
  # @@protoc_insertion_point(class_scope:cartographer.mapping.proto.NormalEstimationOptions2D)
  })
_sym_db.RegisterMessage(NormalEstimationOptions2D)


# @@protoc_insertion_point(module_scope)
