# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cartographer/mapping/proto/pose_graph.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cartographer.mapping.proto import trajectory_pb2 as cartographer_dot_mapping_dot_proto_dot_trajectory__pb2
from cartographer.transform.proto import transform_pb2 as cartographer_dot_transform_dot_proto_dot_transform__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='cartographer/mapping/proto/pose_graph.proto',
  package='cartographer.mapping.proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n+cartographer/mapping/proto/pose_graph.proto\x12\x1a\x63\x61rtographer.mapping.proto\x1a+cartographer/mapping/proto/trajectory.proto\x1a,cartographer/transform/proto/transform.proto\"7\n\x08SubmapId\x12\x15\n\rtrajectory_id\x18\x01 \x01(\x05\x12\x14\n\x0csubmap_index\x18\x02 \x01(\x05\"3\n\x06NodeId\x12\x15\n\rtrajectory_id\x18\x01 \x01(\x05\x12\x12\n\nnode_index\x18\x02 \x01(\x05\"\x98\x05\n\tPoseGraph\x12\x44\n\nconstraint\x18\x02 \x03(\x0b\x32\x30.cartographer.mapping.proto.PoseGraph.Constraint\x12:\n\ntrajectory\x18\x04 \x03(\x0b\x32&.cartographer.mapping.proto.Trajectory\x12J\n\x0elandmark_poses\x18\x05 \x03(\x0b\x32\x32.cartographer.mapping.proto.PoseGraph.LandmarkPose\x1a\xdb\x02\n\nConstraint\x12\x37\n\tsubmap_id\x18\x01 \x01(\x0b\x32$.cartographer.mapping.proto.SubmapId\x12\x33\n\x07node_id\x18\x02 \x01(\x0b\x32\".cartographer.mapping.proto.NodeId\x12<\n\rrelative_pose\x18\x03 \x01(\x0b\x32%.cartographer.transform.proto.Rigid3d\x12\x1a\n\x12translation_weight\x18\x06 \x01(\x01\x12\x17\n\x0frotation_weight\x18\x07 \x01(\x01\x12\x41\n\x03tag\x18\x05 \x01(\x0e\x32\x34.cartographer.mapping.proto.PoseGraph.Constraint.Tag\")\n\x03Tag\x12\x10\n\x0cINTRA_SUBMAP\x10\x00\x12\x10\n\x0cINTER_SUBMAP\x10\x01\x1a_\n\x0cLandmarkPose\x12\x13\n\x0blandmark_id\x18\x01 \x01(\t\x12:\n\x0bglobal_pose\x18\x02 \x01(\x0b\x32%.cartographer.transform.proto.Rigid3db\x06proto3'
  ,
  dependencies=[cartographer_dot_mapping_dot_proto_dot_trajectory__pb2.DESCRIPTOR,cartographer_dot_transform_dot_proto_dot_transform__pb2.DESCRIPTOR,])



_POSEGRAPH_CONSTRAINT_TAG = _descriptor.EnumDescriptor(
  name='Tag',
  full_name='cartographer.mapping.proto.PoseGraph.Constraint.Tag',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INTRA_SUBMAP', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='INTER_SUBMAP', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=803,
  serialized_end=844,
)
_sym_db.RegisterEnumDescriptor(_POSEGRAPH_CONSTRAINT_TAG)


_SUBMAPID = _descriptor.Descriptor(
  name='SubmapId',
  full_name='cartographer.mapping.proto.SubmapId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='trajectory_id', full_name='cartographer.mapping.proto.SubmapId.trajectory_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='submap_index', full_name='cartographer.mapping.proto.SubmapId.submap_index', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=166,
  serialized_end=221,
)


_NODEID = _descriptor.Descriptor(
  name='NodeId',
  full_name='cartographer.mapping.proto.NodeId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='trajectory_id', full_name='cartographer.mapping.proto.NodeId.trajectory_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='node_index', full_name='cartographer.mapping.proto.NodeId.node_index', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=223,
  serialized_end=274,
)


_POSEGRAPH_CONSTRAINT = _descriptor.Descriptor(
  name='Constraint',
  full_name='cartographer.mapping.proto.PoseGraph.Constraint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='submap_id', full_name='cartographer.mapping.proto.PoseGraph.Constraint.submap_id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='node_id', full_name='cartographer.mapping.proto.PoseGraph.Constraint.node_id', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='relative_pose', full_name='cartographer.mapping.proto.PoseGraph.Constraint.relative_pose', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='translation_weight', full_name='cartographer.mapping.proto.PoseGraph.Constraint.translation_weight', index=3,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rotation_weight', full_name='cartographer.mapping.proto.PoseGraph.Constraint.rotation_weight', index=4,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tag', full_name='cartographer.mapping.proto.PoseGraph.Constraint.tag', index=5,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _POSEGRAPH_CONSTRAINT_TAG,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=497,
  serialized_end=844,
)

_POSEGRAPH_LANDMARKPOSE = _descriptor.Descriptor(
  name='LandmarkPose',
  full_name='cartographer.mapping.proto.PoseGraph.LandmarkPose',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='landmark_id', full_name='cartographer.mapping.proto.PoseGraph.LandmarkPose.landmark_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='global_pose', full_name='cartographer.mapping.proto.PoseGraph.LandmarkPose.global_pose', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=846,
  serialized_end=941,
)

_POSEGRAPH = _descriptor.Descriptor(
  name='PoseGraph',
  full_name='cartographer.mapping.proto.PoseGraph',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='constraint', full_name='cartographer.mapping.proto.PoseGraph.constraint', index=0,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='trajectory', full_name='cartographer.mapping.proto.PoseGraph.trajectory', index=1,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='landmark_poses', full_name='cartographer.mapping.proto.PoseGraph.landmark_poses', index=2,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_POSEGRAPH_CONSTRAINT, _POSEGRAPH_LANDMARKPOSE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=277,
  serialized_end=941,
)

_POSEGRAPH_CONSTRAINT.fields_by_name['submap_id'].message_type = _SUBMAPID
_POSEGRAPH_CONSTRAINT.fields_by_name['node_id'].message_type = _NODEID
_POSEGRAPH_CONSTRAINT.fields_by_name['relative_pose'].message_type = cartographer_dot_transform_dot_proto_dot_transform__pb2._RIGID3D
_POSEGRAPH_CONSTRAINT.fields_by_name['tag'].enum_type = _POSEGRAPH_CONSTRAINT_TAG
_POSEGRAPH_CONSTRAINT.containing_type = _POSEGRAPH
_POSEGRAPH_CONSTRAINT_TAG.containing_type = _POSEGRAPH_CONSTRAINT
_POSEGRAPH_LANDMARKPOSE.fields_by_name['global_pose'].message_type = cartographer_dot_transform_dot_proto_dot_transform__pb2._RIGID3D
_POSEGRAPH_LANDMARKPOSE.containing_type = _POSEGRAPH
_POSEGRAPH.fields_by_name['constraint'].message_type = _POSEGRAPH_CONSTRAINT
_POSEGRAPH.fields_by_name['trajectory'].message_type = cartographer_dot_mapping_dot_proto_dot_trajectory__pb2._TRAJECTORY
_POSEGRAPH.fields_by_name['landmark_poses'].message_type = _POSEGRAPH_LANDMARKPOSE
DESCRIPTOR.message_types_by_name['SubmapId'] = _SUBMAPID
DESCRIPTOR.message_types_by_name['NodeId'] = _NODEID
DESCRIPTOR.message_types_by_name['PoseGraph'] = _POSEGRAPH
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SubmapId = _reflection.GeneratedProtocolMessageType('SubmapId', (_message.Message,), {
  'DESCRIPTOR' : _SUBMAPID,
  '__module__' : 'cartographer.mapping.proto.pose_graph_pb2'
  # @@protoc_insertion_point(class_scope:cartographer.mapping.proto.SubmapId)
  })
_sym_db.RegisterMessage(SubmapId)

NodeId = _reflection.GeneratedProtocolMessageType('NodeId', (_message.Message,), {
  'DESCRIPTOR' : _NODEID,
  '__module__' : 'cartographer.mapping.proto.pose_graph_pb2'
  # @@protoc_insertion_point(class_scope:cartographer.mapping.proto.NodeId)
  })
_sym_db.RegisterMessage(NodeId)

PoseGraph = _reflection.GeneratedProtocolMessageType('PoseGraph', (_message.Message,), {

  'Constraint' : _reflection.GeneratedProtocolMessageType('Constraint', (_message.Message,), {
    'DESCRIPTOR' : _POSEGRAPH_CONSTRAINT,
    '__module__' : 'cartographer.mapping.proto.pose_graph_pb2'
    # @@protoc_insertion_point(class_scope:cartographer.mapping.proto.PoseGraph.Constraint)
    })
  ,

  'LandmarkPose' : _reflection.GeneratedProtocolMessageType('LandmarkPose', (_message.Message,), {
    'DESCRIPTOR' : _POSEGRAPH_LANDMARKPOSE,
    '__module__' : 'cartographer.mapping.proto.pose_graph_pb2'
    # @@protoc_insertion_point(class_scope:cartographer.mapping.proto.PoseGraph.LandmarkPose)
    })
  ,
  'DESCRIPTOR' : _POSEGRAPH,
  '__module__' : 'cartographer.mapping.proto.pose_graph_pb2'
  # @@protoc_insertion_point(class_scope:cartographer.mapping.proto.PoseGraph)
  })
_sym_db.RegisterMessage(PoseGraph)
_sym_db.RegisterMessage(PoseGraph.Constraint)
_sym_db.RegisterMessage(PoseGraph.LandmarkPose)


# @@protoc_insertion_point(module_scope)
