# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cartographer/mapping/proto/pose_extrapolator_options.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cartographer.common.proto import ceres_solver_options_pb2 as cartographer_dot_common_dot_proto_dot_ceres__solver__options__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='cartographer/mapping/proto/pose_extrapolator_options.proto',
  package='cartographer.mapping.proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n:cartographer/mapping/proto/pose_extrapolator_options.proto\x12\x1a\x63\x61rtographer.mapping.proto\x1a\x34\x63\x61rtographer/common/proto/ceres_solver_options.proto\"i\n\'ConstantVelocityPoseExtrapolatorOptions\x12!\n\x19imu_gravity_time_constant\x18\x01 \x01(\x01\x12\x1b\n\x13pose_queue_duration\x18\x02 \x01(\x01\"\xe3\x02\n\x1fImuBasedPoseExtrapolatorOptions\x12\x1b\n\x13pose_queue_duration\x18\x01 \x01(\x01\x12\x18\n\x10gravity_constant\x18\x02 \x01(\x01\x12\x1f\n\x17pose_translation_weight\x18\x03 \x01(\x01\x12\x1c\n\x14pose_rotation_weight\x18\x04 \x01(\x01\x12\x1f\n\x17imu_acceleration_weight\x18\x05 \x01(\x01\x12\x1b\n\x13imu_rotation_weight\x18\x06 \x01(\x01\x12\x45\n\x0esolver_options\x18\x07 \x01(\x0b\x32-.cartographer.common.proto.CeresSolverOptions\x12#\n\x1bodometry_translation_weight\x18\x08 \x01(\x01\x12 \n\x18odometry_rotation_weight\x18\t \x01(\x01\"\xe0\x01\n\x17PoseExtrapolatorOptions\x12\x15\n\ruse_imu_based\x18\x01 \x01(\x08\x12^\n\x11\x63onstant_velocity\x18\x02 \x01(\x0b\x32\x43.cartographer.mapping.proto.ConstantVelocityPoseExtrapolatorOptions\x12N\n\timu_based\x18\x03 \x01(\x0b\x32;.cartographer.mapping.proto.ImuBasedPoseExtrapolatorOptionsb\x06proto3'
  ,
  dependencies=[cartographer_dot_common_dot_proto_dot_ceres__solver__options__pb2.DESCRIPTOR,])




_CONSTANTVELOCITYPOSEEXTRAPOLATOROPTIONS = _descriptor.Descriptor(
  name='ConstantVelocityPoseExtrapolatorOptions',
  full_name='cartographer.mapping.proto.ConstantVelocityPoseExtrapolatorOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='imu_gravity_time_constant', full_name='cartographer.mapping.proto.ConstantVelocityPoseExtrapolatorOptions.imu_gravity_time_constant', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pose_queue_duration', full_name='cartographer.mapping.proto.ConstantVelocityPoseExtrapolatorOptions.pose_queue_duration', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=144,
  serialized_end=249,
)


_IMUBASEDPOSEEXTRAPOLATOROPTIONS = _descriptor.Descriptor(
  name='ImuBasedPoseExtrapolatorOptions',
  full_name='cartographer.mapping.proto.ImuBasedPoseExtrapolatorOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='pose_queue_duration', full_name='cartographer.mapping.proto.ImuBasedPoseExtrapolatorOptions.pose_queue_duration', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gravity_constant', full_name='cartographer.mapping.proto.ImuBasedPoseExtrapolatorOptions.gravity_constant', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pose_translation_weight', full_name='cartographer.mapping.proto.ImuBasedPoseExtrapolatorOptions.pose_translation_weight', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pose_rotation_weight', full_name='cartographer.mapping.proto.ImuBasedPoseExtrapolatorOptions.pose_rotation_weight', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='imu_acceleration_weight', full_name='cartographer.mapping.proto.ImuBasedPoseExtrapolatorOptions.imu_acceleration_weight', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='imu_rotation_weight', full_name='cartographer.mapping.proto.ImuBasedPoseExtrapolatorOptions.imu_rotation_weight', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='solver_options', full_name='cartographer.mapping.proto.ImuBasedPoseExtrapolatorOptions.solver_options', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='odometry_translation_weight', full_name='cartographer.mapping.proto.ImuBasedPoseExtrapolatorOptions.odometry_translation_weight', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='odometry_rotation_weight', full_name='cartographer.mapping.proto.ImuBasedPoseExtrapolatorOptions.odometry_rotation_weight', index=8,
      number=9, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=252,
  serialized_end=607,
)


_POSEEXTRAPOLATOROPTIONS = _descriptor.Descriptor(
  name='PoseExtrapolatorOptions',
  full_name='cartographer.mapping.proto.PoseExtrapolatorOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='use_imu_based', full_name='cartographer.mapping.proto.PoseExtrapolatorOptions.use_imu_based', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='constant_velocity', full_name='cartographer.mapping.proto.PoseExtrapolatorOptions.constant_velocity', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='imu_based', full_name='cartographer.mapping.proto.PoseExtrapolatorOptions.imu_based', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=610,
  serialized_end=834,
)

_IMUBASEDPOSEEXTRAPOLATOROPTIONS.fields_by_name['solver_options'].message_type = cartographer_dot_common_dot_proto_dot_ceres__solver__options__pb2._CERESSOLVEROPTIONS
_POSEEXTRAPOLATOROPTIONS.fields_by_name['constant_velocity'].message_type = _CONSTANTVELOCITYPOSEEXTRAPOLATOROPTIONS
_POSEEXTRAPOLATOROPTIONS.fields_by_name['imu_based'].message_type = _IMUBASEDPOSEEXTRAPOLATOROPTIONS
DESCRIPTOR.message_types_by_name['ConstantVelocityPoseExtrapolatorOptions'] = _CONSTANTVELOCITYPOSEEXTRAPOLATOROPTIONS
DESCRIPTOR.message_types_by_name['ImuBasedPoseExtrapolatorOptions'] = _IMUBASEDPOSEEXTRAPOLATOROPTIONS
DESCRIPTOR.message_types_by_name['PoseExtrapolatorOptions'] = _POSEEXTRAPOLATOROPTIONS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ConstantVelocityPoseExtrapolatorOptions = _reflection.GeneratedProtocolMessageType('ConstantVelocityPoseExtrapolatorOptions', (_message.Message,), {
  'DESCRIPTOR' : _CONSTANTVELOCITYPOSEEXTRAPOLATOROPTIONS,
  '__module__' : 'cartographer.mapping.proto.pose_extrapolator_options_pb2'
  # @@protoc_insertion_point(class_scope:cartographer.mapping.proto.ConstantVelocityPoseExtrapolatorOptions)
  })
_sym_db.RegisterMessage(ConstantVelocityPoseExtrapolatorOptions)

ImuBasedPoseExtrapolatorOptions = _reflection.GeneratedProtocolMessageType('ImuBasedPoseExtrapolatorOptions', (_message.Message,), {
  'DESCRIPTOR' : _IMUBASEDPOSEEXTRAPOLATOROPTIONS,
  '__module__' : 'cartographer.mapping.proto.pose_extrapolator_options_pb2'
  # @@protoc_insertion_point(class_scope:cartographer.mapping.proto.ImuBasedPoseExtrapolatorOptions)
  })
_sym_db.RegisterMessage(ImuBasedPoseExtrapolatorOptions)

PoseExtrapolatorOptions = _reflection.GeneratedProtocolMessageType('PoseExtrapolatorOptions', (_message.Message,), {
  'DESCRIPTOR' : _POSEEXTRAPOLATOROPTIONS,
  '__module__' : 'cartographer.mapping.proto.pose_extrapolator_options_pb2'
  # @@protoc_insertion_point(class_scope:cartographer.mapping.proto.PoseExtrapolatorOptions)
  })
_sym_db.RegisterMessage(PoseExtrapolatorOptions)


# @@protoc_insertion_point(module_scope)
