# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cartographer/mapping/proto/probability_grid_range_data_inserter_options_2d.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cartographer/mapping/proto/probability_grid_range_data_inserter_options_2d.proto',
  package='cartographer.mapping.proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\nPcartographer/mapping/proto/probability_grid_range_data_inserter_options_2d.proto\x12\x1a\x63\x61rtographer.mapping.proto\"y\n)ProbabilityGridRangeDataInserterOptions2D\x12\x17\n\x0fhit_probability\x18\x01 \x01(\x01\x12\x18\n\x10miss_probability\x18\x02 \x01(\x01\x12\x19\n\x11insert_free_space\x18\x03 \x01(\x08\x62\x06proto3'
)




_PROBABILITYGRIDRANGEDATAINSERTEROPTIONS2D = _descriptor.Descriptor(
  name='ProbabilityGridRangeDataInserterOptions2D',
  full_name='cartographer.mapping.proto.ProbabilityGridRangeDataInserterOptions2D',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='hit_probability', full_name='cartographer.mapping.proto.ProbabilityGridRangeDataInserterOptions2D.hit_probability', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='miss_probability', full_name='cartographer.mapping.proto.ProbabilityGridRangeDataInserterOptions2D.miss_probability', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='insert_free_space', full_name='cartographer.mapping.proto.ProbabilityGridRangeDataInserterOptions2D.insert_free_space', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=233,
)

DESCRIPTOR.message_types_by_name['ProbabilityGridRangeDataInserterOptions2D'] = _PROBABILITYGRIDRANGEDATAINSERTEROPTIONS2D
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProbabilityGridRangeDataInserterOptions2D = _reflection.GeneratedProtocolMessageType('ProbabilityGridRangeDataInserterOptions2D', (_message.Message,), {
  'DESCRIPTOR' : _PROBABILITYGRIDRANGEDATAINSERTEROPTIONS2D,
  '__module__' : 'cartographer.mapping.proto.probability_grid_range_data_inserter_options_2d_pb2'
  # @@protoc_insertion_point(class_scope:cartographer.mapping.proto.ProbabilityGridRangeDataInserterOptions2D)
  })
_sym_db.RegisterMessage(ProbabilityGridRangeDataInserterOptions2D)


# @@protoc_insertion_point(module_scope)
