# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cartographer/mapping/proto/probability_grid.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cartographer/mapping/proto/probability_grid.proto',
  package='cartographer.mapping.proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n1cartographer/mapping/proto/probability_grid.proto\x12\x1a\x63\x61rtographer.mapping.proto\"\x11\n\x0fProbabilityGridb\x06proto3'
)




_PROBABILITYGRID = _descriptor.Descriptor(
  name='ProbabilityGrid',
  full_name='cartographer.mapping.proto.ProbabilityGrid',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=98,
)

DESCRIPTOR.message_types_by_name['ProbabilityGrid'] = _PROBABILITYGRID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProbabilityGrid = _reflection.GeneratedProtocolMessageType('ProbabilityGrid', (_message.Message,), {
  'DESCRIPTOR' : _PROBABILITYGRID,
  '__module__' : 'cartographer.mapping.proto.probability_grid_pb2'
  # @@protoc_insertion_point(class_scope:cartographer.mapping.proto.ProbabilityGrid)
  })
_sym_db.RegisterMessage(ProbabilityGrid)


# @@protoc_insertion_point(module_scope)
