# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cartographer/mapping/proto/range_data_inserter_options_3d.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cartographer/mapping/proto/range_data_inserter_options_3d.proto',
  package='cartographer.mapping.proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n?cartographer/mapping/proto/range_data_inserter_options_3d.proto\x12\x1a\x63\x61rtographer.mapping.proto\"\x8b\x01\n\x1aRangeDataInserterOptions3D\x12\x17\n\x0fhit_probability\x18\x01 \x01(\x01\x12\x18\n\x10miss_probability\x18\x02 \x01(\x01\x12\x1d\n\x15num_free_space_voxels\x18\x03 \x01(\x05\x12\x1b\n\x13intensity_threshold\x18\x04 \x01(\x02\x62\x06proto3'
)




_RANGEDATAINSERTEROPTIONS3D = _descriptor.Descriptor(
  name='RangeDataInserterOptions3D',
  full_name='cartographer.mapping.proto.RangeDataInserterOptions3D',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='hit_probability', full_name='cartographer.mapping.proto.RangeDataInserterOptions3D.hit_probability', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='miss_probability', full_name='cartographer.mapping.proto.RangeDataInserterOptions3D.miss_probability', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_free_space_voxels', full_name='cartographer.mapping.proto.RangeDataInserterOptions3D.num_free_space_voxels', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='intensity_threshold', full_name='cartographer.mapping.proto.RangeDataInserterOptions3D.intensity_threshold', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=96,
  serialized_end=235,
)

DESCRIPTOR.message_types_by_name['RangeDataInserterOptions3D'] = _RANGEDATAINSERTEROPTIONS3D
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RangeDataInserterOptions3D = _reflection.GeneratedProtocolMessageType('RangeDataInserterOptions3D', (_message.Message,), {
  'DESCRIPTOR' : _RANGEDATAINSERTEROPTIONS3D,
  '__module__' : 'cartographer.mapping.proto.range_data_inserter_options_3d_pb2'
  # @@protoc_insertion_point(class_scope:cartographer.mapping.proto.RangeDataInserterOptions3D)
  })
_sym_db.RegisterMessage(RangeDataInserterOptions3D)


# @@protoc_insertion_point(module_scope)
