# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cartographer/mapping/proto/range_data_inserter_options.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cartographer.mapping.proto import probability_grid_range_data_inserter_options_2d_pb2 as cartographer_dot_mapping_dot_proto_dot_probability__grid__range__data__inserter__options__2d__pb2
from cartographer.mapping.proto import tsdf_range_data_inserter_options_2d_pb2 as cartographer_dot_mapping_dot_proto_dot_tsdf__range__data__inserter__options__2d__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='cartographer/mapping/proto/range_data_inserter_options.proto',
  package='cartographer.mapping.proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n<cartographer/mapping/proto/range_data_inserter_options.proto\x12\x1a\x63\x61rtographer.mapping.proto\x1aPcartographer/mapping/proto/probability_grid_range_data_inserter_options_2d.proto\x1a\x44\x63\x61rtographer/mapping/proto/tsdf_range_data_inserter_options_2d.proto\"\xd8\x03\n\x18RangeDataInserterOptions\x12l\n\x18range_data_inserter_type\x18\x01 \x01(\x0e\x32J.cartographer.mapping.proto.RangeDataInserterOptions.RangeDataInserterType\x12~\n/probability_grid_range_data_inserter_options_2d\x18\x02 \x01(\x0b\x32\x45.cartographer.mapping.proto.ProbabilityGridRangeDataInserterOptions2D\x12g\n#tsdf_range_data_inserter_options_2d\x18\x03 \x01(\x0b\x32:.cartographer.mapping.proto.TSDFRangeDataInserterOptions2D\"e\n\x15RangeDataInserterType\x12\x14\n\x10INVALID_INSERTER\x10\x00\x12 \n\x1cPROBABILITY_GRID_INSERTER_2D\x10\x01\x12\x14\n\x10TSDF_INSERTER_2D\x10\x02\x62\x06proto3'
  ,
  dependencies=[cartographer_dot_mapping_dot_proto_dot_probability__grid__range__data__inserter__options__2d__pb2.DESCRIPTOR,cartographer_dot_mapping_dot_proto_dot_tsdf__range__data__inserter__options__2d__pb2.DESCRIPTOR,])



_RANGEDATAINSERTEROPTIONS_RANGEDATAINSERTERTYPE = _descriptor.EnumDescriptor(
  name='RangeDataInserterType',
  full_name='cartographer.mapping.proto.RangeDataInserterOptions.RangeDataInserterType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INVALID_INSERTER', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PROBABILITY_GRID_INSERTER_2D', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TSDF_INSERTER_2D', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=616,
  serialized_end=717,
)
_sym_db.RegisterEnumDescriptor(_RANGEDATAINSERTEROPTIONS_RANGEDATAINSERTERTYPE)


_RANGEDATAINSERTEROPTIONS = _descriptor.Descriptor(
  name='RangeDataInserterOptions',
  full_name='cartographer.mapping.proto.RangeDataInserterOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='range_data_inserter_type', full_name='cartographer.mapping.proto.RangeDataInserterOptions.range_data_inserter_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='probability_grid_range_data_inserter_options_2d', full_name='cartographer.mapping.proto.RangeDataInserterOptions.probability_grid_range_data_inserter_options_2d', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tsdf_range_data_inserter_options_2d', full_name='cartographer.mapping.proto.RangeDataInserterOptions.tsdf_range_data_inserter_options_2d', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _RANGEDATAINSERTEROPTIONS_RANGEDATAINSERTERTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=245,
  serialized_end=717,
)

_RANGEDATAINSERTEROPTIONS.fields_by_name['range_data_inserter_type'].enum_type = _RANGEDATAINSERTEROPTIONS_RANGEDATAINSERTERTYPE
_RANGEDATAINSERTEROPTIONS.fields_by_name['probability_grid_range_data_inserter_options_2d'].message_type = cartographer_dot_mapping_dot_proto_dot_probability__grid__range__data__inserter__options__2d__pb2._PROBABILITYGRIDRANGEDATAINSERTEROPTIONS2D
_RANGEDATAINSERTEROPTIONS.fields_by_name['tsdf_range_data_inserter_options_2d'].message_type = cartographer_dot_mapping_dot_proto_dot_tsdf__range__data__inserter__options__2d__pb2._TSDFRANGEDATAINSERTEROPTIONS2D
_RANGEDATAINSERTEROPTIONS_RANGEDATAINSERTERTYPE.containing_type = _RANGEDATAINSERTEROPTIONS
DESCRIPTOR.message_types_by_name['RangeDataInserterOptions'] = _RANGEDATAINSERTEROPTIONS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RangeDataInserterOptions = _reflection.GeneratedProtocolMessageType('RangeDataInserterOptions', (_message.Message,), {
  'DESCRIPTOR' : _RANGEDATAINSERTEROPTIONS,
  '__module__' : 'cartographer.mapping.proto.range_data_inserter_options_pb2'
  # @@protoc_insertion_point(class_scope:cartographer.mapping.proto.RangeDataInserterOptions)
  })
_sym_db.RegisterMessage(RangeDataInserterOptions)


# @@protoc_insertion_point(module_scope)
