# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cartographer/mapping/proto/submaps_options_3d.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cartographer.mapping.proto import range_data_inserter_options_3d_pb2 as cartographer_dot_mapping_dot_proto_dot_range__data__inserter__options__3d__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='cartographer/mapping/proto/submaps_options_3d.proto',
  package='cartographer.mapping.proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n3cartographer/mapping/proto/submaps_options_3d.proto\x12\x1a\x63\x61rtographer.mapping.proto\x1a?cartographer/mapping/proto/range_data_inserter_options_3d.proto\"\xdb\x01\n\x10SubmapsOptions3D\x12\x17\n\x0fhigh_resolution\x18\x01 \x01(\x01\x12!\n\x19high_resolution_max_range\x18\x04 \x01(\x01\x12\x16\n\x0elow_resolution\x18\x05 \x01(\x01\x12\x16\n\x0enum_range_data\x18\x02 \x01(\x05\x12[\n\x1brange_data_inserter_options\x18\x03 \x01(\x0b\x32\x36.cartographer.mapping.proto.RangeDataInserterOptions3Db\x06proto3'
  ,
  dependencies=[cartographer_dot_mapping_dot_proto_dot_range__data__inserter__options__3d__pb2.DESCRIPTOR,])




_SUBMAPSOPTIONS3D = _descriptor.Descriptor(
  name='SubmapsOptions3D',
  full_name='cartographer.mapping.proto.SubmapsOptions3D',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='high_resolution', full_name='cartographer.mapping.proto.SubmapsOptions3D.high_resolution', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='high_resolution_max_range', full_name='cartographer.mapping.proto.SubmapsOptions3D.high_resolution_max_range', index=1,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='low_resolution', full_name='cartographer.mapping.proto.SubmapsOptions3D.low_resolution', index=2,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_range_data', full_name='cartographer.mapping.proto.SubmapsOptions3D.num_range_data', index=3,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='range_data_inserter_options', full_name='cartographer.mapping.proto.SubmapsOptions3D.range_data_inserter_options', index=4,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=149,
  serialized_end=368,
)

_SUBMAPSOPTIONS3D.fields_by_name['range_data_inserter_options'].message_type = cartographer_dot_mapping_dot_proto_dot_range__data__inserter__options__3d__pb2._RANGEDATAINSERTEROPTIONS3D
DESCRIPTOR.message_types_by_name['SubmapsOptions3D'] = _SUBMAPSOPTIONS3D
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SubmapsOptions3D = _reflection.GeneratedProtocolMessageType('SubmapsOptions3D', (_message.Message,), {
  'DESCRIPTOR' : _SUBMAPSOPTIONS3D,
  '__module__' : 'cartographer.mapping.proto.submaps_options_3d_pb2'
  # @@protoc_insertion_point(class_scope:cartographer.mapping.proto.SubmapsOptions3D)
  })
_sym_db.RegisterMessage(SubmapsOptions3D)


# @@protoc_insertion_point(module_scope)
