# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cartographer/mapping/proto/submaps_options_2d.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cartographer.mapping.proto import grid_2d_options_pb2 as cartographer_dot_mapping_dot_proto_dot_grid__2d__options__pb2
from cartographer.mapping.proto import range_data_inserter_options_pb2 as cartographer_dot_mapping_dot_proto_dot_range__data__inserter__options__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='cartographer/mapping/proto/submaps_options_2d.proto',
  package='cartographer.mapping.proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n3cartographer/mapping/proto/submaps_options_2d.proto\x12\x1a\x63\x61rtographer.mapping.proto\x1a\x30\x63\x61rtographer/mapping/proto/grid_2d_options.proto\x1a<cartographer/mapping/proto/range_data_inserter_options.proto\"\xc9\x01\n\x10SubmapsOptions2D\x12\x16\n\x0enum_range_data\x18\x01 \x01(\x05\x12\x42\n\x0fgrid_options_2d\x18\x02 \x01(\x0b\x32).cartographer.mapping.proto.GridOptions2D\x12Y\n\x1brange_data_inserter_options\x18\x03 \x01(\x0b\x32\x34.cartographer.mapping.proto.RangeDataInserterOptionsb\x06proto3'
  ,
  dependencies=[cartographer_dot_mapping_dot_proto_dot_grid__2d__options__pb2.DESCRIPTOR,cartographer_dot_mapping_dot_proto_dot_range__data__inserter__options__pb2.DESCRIPTOR,])




_SUBMAPSOPTIONS2D = _descriptor.Descriptor(
  name='SubmapsOptions2D',
  full_name='cartographer.mapping.proto.SubmapsOptions2D',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='num_range_data', full_name='cartographer.mapping.proto.SubmapsOptions2D.num_range_data', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='grid_options_2d', full_name='cartographer.mapping.proto.SubmapsOptions2D.grid_options_2d', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='range_data_inserter_options', full_name='cartographer.mapping.proto.SubmapsOptions2D.range_data_inserter_options', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=196,
  serialized_end=397,
)

_SUBMAPSOPTIONS2D.fields_by_name['grid_options_2d'].message_type = cartographer_dot_mapping_dot_proto_dot_grid__2d__options__pb2._GRIDOPTIONS2D
_SUBMAPSOPTIONS2D.fields_by_name['range_data_inserter_options'].message_type = cartographer_dot_mapping_dot_proto_dot_range__data__inserter__options__pb2._RANGEDATAINSERTEROPTIONS
DESCRIPTOR.message_types_by_name['SubmapsOptions2D'] = _SUBMAPSOPTIONS2D
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SubmapsOptions2D = _reflection.GeneratedProtocolMessageType('SubmapsOptions2D', (_message.Message,), {
  'DESCRIPTOR' : _SUBMAPSOPTIONS2D,
  '__module__' : 'cartographer.mapping.proto.submaps_options_2d_pb2'
  # @@protoc_insertion_point(class_scope:cartographer.mapping.proto.SubmapsOptions2D)
  })
_sym_db.RegisterMessage(SubmapsOptions2D)


# @@protoc_insertion_point(module_scope)
