# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cartographer/mapping/proto/tsdf_2d.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cartographer/mapping/proto/tsdf_2d.proto',
  package='cartographer.mapping.proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n(cartographer/mapping/proto/tsdf_2d.proto\x12\x1a\x63\x61rtographer.mapping.proto\"O\n\x06TSDF2D\x12\x1b\n\x13truncation_distance\x18\x01 \x01(\x02\x12\x12\n\nmax_weight\x18\x02 \x01(\x02\x12\x14\n\x0cweight_cells\x18\x03 \x03(\x05\x62\x06proto3'
)




_TSDF2D = _descriptor.Descriptor(
  name='TSDF2D',
  full_name='cartographer.mapping.proto.TSDF2D',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='truncation_distance', full_name='cartographer.mapping.proto.TSDF2D.truncation_distance', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max_weight', full_name='cartographer.mapping.proto.TSDF2D.max_weight', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='weight_cells', full_name='cartographer.mapping.proto.TSDF2D.weight_cells', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=151,
)

DESCRIPTOR.message_types_by_name['TSDF2D'] = _TSDF2D
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TSDF2D = _reflection.GeneratedProtocolMessageType('TSDF2D', (_message.Message,), {
  'DESCRIPTOR' : _TSDF2D,
  '__module__' : 'cartographer.mapping.proto.tsdf_2d_pb2'
  # @@protoc_insertion_point(class_scope:cartographer.mapping.proto.TSDF2D)
  })
_sym_db.RegisterMessage(TSDF2D)


# @@protoc_insertion_point(module_scope)
