# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cartographer/mapping/proto/tsdf_range_data_inserter_options_2d.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cartographer.mapping.proto import normal_estimation_options_2d_pb2 as cartographer_dot_mapping_dot_proto_dot_normal__estimation__options__2d__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='cartographer/mapping/proto/tsdf_range_data_inserter_options_2d.proto',
  package='cartographer.mapping.proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\nDcartographer/mapping/proto/tsdf_range_data_inserter_options_2d.proto\x12\x1a\x63\x61rtographer.mapping.proto\x1a=cartographer/mapping/proto/normal_estimation_options_2d.proto\"\x9b\x03\n\x1eTSDFRangeDataInserterOptions2D\x12\x1b\n\x13truncation_distance\x18\x01 \x01(\x01\x12\x16\n\x0emaximum_weight\x18\x02 \x01(\x01\x12\x19\n\x11update_free_space\x18\x03 \x01(\x08\x12X\n\x19normal_estimation_options\x18\x04 \x01(\x0b\x32\x35.cartographer.mapping.proto.NormalEstimationOptions2D\x12+\n#project_sdf_distance_to_scan_normal\x18\x05 \x01(\x08\x12$\n\x1cupdate_weight_range_exponent\x18\x06 \x01(\x05\x12?\n7update_weight_angle_scan_normal_to_ray_kernel_bandwidth\x18\x07 \x01(\x01\x12;\n3update_weight_distance_cell_to_hit_kernel_bandwidth\x18\x08 \x01(\x01\x62\x06proto3'
  ,
  dependencies=[cartographer_dot_mapping_dot_proto_dot_normal__estimation__options__2d__pb2.DESCRIPTOR,])




_TSDFRANGEDATAINSERTEROPTIONS2D = _descriptor.Descriptor(
  name='TSDFRangeDataInserterOptions2D',
  full_name='cartographer.mapping.proto.TSDFRangeDataInserterOptions2D',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='truncation_distance', full_name='cartographer.mapping.proto.TSDFRangeDataInserterOptions2D.truncation_distance', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='maximum_weight', full_name='cartographer.mapping.proto.TSDFRangeDataInserterOptions2D.maximum_weight', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='update_free_space', full_name='cartographer.mapping.proto.TSDFRangeDataInserterOptions2D.update_free_space', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='normal_estimation_options', full_name='cartographer.mapping.proto.TSDFRangeDataInserterOptions2D.normal_estimation_options', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='project_sdf_distance_to_scan_normal', full_name='cartographer.mapping.proto.TSDFRangeDataInserterOptions2D.project_sdf_distance_to_scan_normal', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='update_weight_range_exponent', full_name='cartographer.mapping.proto.TSDFRangeDataInserterOptions2D.update_weight_range_exponent', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='update_weight_angle_scan_normal_to_ray_kernel_bandwidth', full_name='cartographer.mapping.proto.TSDFRangeDataInserterOptions2D.update_weight_angle_scan_normal_to_ray_kernel_bandwidth', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='update_weight_distance_cell_to_hit_kernel_bandwidth', full_name='cartographer.mapping.proto.TSDFRangeDataInserterOptions2D.update_weight_distance_cell_to_hit_kernel_bandwidth', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=164,
  serialized_end=575,
)

_TSDFRANGEDATAINSERTEROPTIONS2D.fields_by_name['normal_estimation_options'].message_type = cartographer_dot_mapping_dot_proto_dot_normal__estimation__options__2d__pb2._NORMALESTIMATIONOPTIONS2D
DESCRIPTOR.message_types_by_name['TSDFRangeDataInserterOptions2D'] = _TSDFRANGEDATAINSERTEROPTIONS2D
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TSDFRangeDataInserterOptions2D = _reflection.GeneratedProtocolMessageType('TSDFRangeDataInserterOptions2D', (_message.Message,), {
  'DESCRIPTOR' : _TSDFRANGEDATAINSERTEROPTIONS2D,
  '__module__' : 'cartographer.mapping.proto.tsdf_range_data_inserter_options_2d_pb2'
  # @@protoc_insertion_point(class_scope:cartographer.mapping.proto.TSDFRangeDataInserterOptions2D)
  })
_sym_db.RegisterMessage(TSDFRangeDataInserterOptions2D)


# @@protoc_insertion_point(module_scope)
