# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cartographer/sensor/proto/adaptive_voxel_filter_options.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cartographer/sensor/proto/adaptive_voxel_filter_options.proto',
  package='cartographer.sensor.proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n=cartographer/sensor/proto/adaptive_voxel_filter_options.proto\x12\x19\x63\x61rtographer.sensor.proto\"[\n\x1a\x41\x64\x61ptiveVoxelFilterOptions\x12\x12\n\nmax_length\x18\x01 \x01(\x02\x12\x16\n\x0emin_num_points\x18\x02 \x01(\x02\x12\x11\n\tmax_range\x18\x03 \x01(\x02\x62\x06proto3'
)




_ADAPTIVEVOXELFILTEROPTIONS = _descriptor.Descriptor(
  name='AdaptiveVoxelFilterOptions',
  full_name='cartographer.sensor.proto.AdaptiveVoxelFilterOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='max_length', full_name='cartographer.sensor.proto.AdaptiveVoxelFilterOptions.max_length', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='min_num_points', full_name='cartographer.sensor.proto.AdaptiveVoxelFilterOptions.min_num_points', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max_range', full_name='cartographer.sensor.proto.AdaptiveVoxelFilterOptions.max_range', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=183,
)

DESCRIPTOR.message_types_by_name['AdaptiveVoxelFilterOptions'] = _ADAPTIVEVOXELFILTEROPTIONS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AdaptiveVoxelFilterOptions = _reflection.GeneratedProtocolMessageType('AdaptiveVoxelFilterOptions', (_message.Message,), {
  'DESCRIPTOR' : _ADAPTIVEVOXELFILTEROPTIONS,
  '__module__' : 'cartographer.sensor.proto.adaptive_voxel_filter_options_pb2'
  # @@protoc_insertion_point(class_scope:cartographer.sensor.proto.AdaptiveVoxelFilterOptions)
  })
_sym_db.RegisterMessage(AdaptiveVoxelFilterOptions)


# @@protoc_insertion_point(module_scope)
