# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cartographer/transform/proto/timestamped_transform.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cartographer.transform.proto import transform_pb2 as cartographer_dot_transform_dot_proto_dot_transform__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='cartographer/transform/proto/timestamped_transform.proto',
  package='cartographer.transform.proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n8cartographer/transform/proto/timestamped_transform.proto\x12\x1c\x63\x61rtographer.transform.proto\x1a,cartographer/transform/proto/transform.proto\"^\n\x14TimestampedTransform\x12\x0c\n\x04time\x18\x01 \x01(\x03\x12\x38\n\ttransform\x18\x02 \x01(\x0b\x32%.cartographer.transform.proto.Rigid3db\x06proto3'
  ,
  dependencies=[cartographer_dot_transform_dot_proto_dot_transform__pb2.DESCRIPTOR,])




_TIMESTAMPEDTRANSFORM = _descriptor.Descriptor(
  name='TimestampedTransform',
  full_name='cartographer.transform.proto.TimestampedTransform',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='cartographer.transform.proto.TimestampedTransform.time', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='transform', full_name='cartographer.transform.proto.TimestampedTransform.transform', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=136,
  serialized_end=230,
)

_TIMESTAMPEDTRANSFORM.fields_by_name['transform'].message_type = cartographer_dot_transform_dot_proto_dot_transform__pb2._RIGID3D
DESCRIPTOR.message_types_by_name['TimestampedTransform'] = _TIMESTAMPEDTRANSFORM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TimestampedTransform = _reflection.GeneratedProtocolMessageType('TimestampedTransform', (_message.Message,), {
  'DESCRIPTOR' : _TIMESTAMPEDTRANSFORM,
  '__module__' : 'cartographer.transform.proto.timestamped_transform_pb2'
  # @@protoc_insertion_point(class_scope:cartographer.transform.proto.TimestampedTransform)
  })
_sym_db.RegisterMessage(TimestampedTransform)


# @@protoc_insertion_point(module_scope)
