# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cartographer/mapping/proto/scan_matching/ceres_scan_matcher_options_3d.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cartographer.common.proto import ceres_solver_options_pb2 as cartographer_dot_common_dot_proto_dot_ceres__solver__options__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='cartographer/mapping/proto/scan_matching/ceres_scan_matcher_options_3d.proto',
  package='cartographer.mapping.scan_matching.proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\nLcartographer/mapping/proto/scan_matching/ceres_scan_matcher_options_3d.proto\x12(cartographer.mapping.scan_matching.proto\x1a\x34\x63\x61rtographer/common/proto/ceres_solver_options.proto\"`\n\x1cIntensityCostFunctionOptions\x12\x0e\n\x06weight\x18\x01 \x01(\x01\x12\x13\n\x0bhuber_scale\x18\x02 \x01(\x01\x12\x1b\n\x13intensity_threshold\x18\x03 \x01(\x02\"\xc8\x02\n\x19\x43\x65resScanMatcherOptions3D\x12\x1d\n\x15occupied_space_weight\x18\x01 \x03(\x01\x12\x1a\n\x12translation_weight\x18\x02 \x01(\x01\x12\x17\n\x0frotation_weight\x18\x03 \x01(\x01\x12\x19\n\x11only_optimize_yaw\x18\x05 \x01(\x08\x12K\n\x14\x63\x65res_solver_options\x18\x06 \x01(\x0b\x32-.cartographer.common.proto.CeresSolverOptions\x12o\n\x1fintensity_cost_function_options\x18\x07 \x03(\x0b\x32\x46.cartographer.mapping.scan_matching.proto.IntensityCostFunctionOptionsb\x06proto3'
  ,
  dependencies=[cartographer_dot_common_dot_proto_dot_ceres__solver__options__pb2.DESCRIPTOR,])




_INTENSITYCOSTFUNCTIONOPTIONS = _descriptor.Descriptor(
  name='IntensityCostFunctionOptions',
  full_name='cartographer.mapping.scan_matching.proto.IntensityCostFunctionOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='weight', full_name='cartographer.mapping.scan_matching.proto.IntensityCostFunctionOptions.weight', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='huber_scale', full_name='cartographer.mapping.scan_matching.proto.IntensityCostFunctionOptions.huber_scale', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='intensity_threshold', full_name='cartographer.mapping.scan_matching.proto.IntensityCostFunctionOptions.intensity_threshold', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=176,
  serialized_end=272,
)


_CERESSCANMATCHEROPTIONS3D = _descriptor.Descriptor(
  name='CeresScanMatcherOptions3D',
  full_name='cartographer.mapping.scan_matching.proto.CeresScanMatcherOptions3D',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='occupied_space_weight', full_name='cartographer.mapping.scan_matching.proto.CeresScanMatcherOptions3D.occupied_space_weight', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='translation_weight', full_name='cartographer.mapping.scan_matching.proto.CeresScanMatcherOptions3D.translation_weight', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rotation_weight', full_name='cartographer.mapping.scan_matching.proto.CeresScanMatcherOptions3D.rotation_weight', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='only_optimize_yaw', full_name='cartographer.mapping.scan_matching.proto.CeresScanMatcherOptions3D.only_optimize_yaw', index=3,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ceres_solver_options', full_name='cartographer.mapping.scan_matching.proto.CeresScanMatcherOptions3D.ceres_solver_options', index=4,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='intensity_cost_function_options', full_name='cartographer.mapping.scan_matching.proto.CeresScanMatcherOptions3D.intensity_cost_function_options', index=5,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=275,
  serialized_end=603,
)

_CERESSCANMATCHEROPTIONS3D.fields_by_name['ceres_solver_options'].message_type = cartographer_dot_common_dot_proto_dot_ceres__solver__options__pb2._CERESSOLVEROPTIONS
_CERESSCANMATCHEROPTIONS3D.fields_by_name['intensity_cost_function_options'].message_type = _INTENSITYCOSTFUNCTIONOPTIONS
DESCRIPTOR.message_types_by_name['IntensityCostFunctionOptions'] = _INTENSITYCOSTFUNCTIONOPTIONS
DESCRIPTOR.message_types_by_name['CeresScanMatcherOptions3D'] = _CERESSCANMATCHEROPTIONS3D
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IntensityCostFunctionOptions = _reflection.GeneratedProtocolMessageType('IntensityCostFunctionOptions', (_message.Message,), {
  'DESCRIPTOR' : _INTENSITYCOSTFUNCTIONOPTIONS,
  '__module__' : 'cartographer.mapping.proto.scan_matching.ceres_scan_matcher_options_3d_pb2'
  # @@protoc_insertion_point(class_scope:cartographer.mapping.scan_matching.proto.IntensityCostFunctionOptions)
  })
_sym_db.RegisterMessage(IntensityCostFunctionOptions)

CeresScanMatcherOptions3D = _reflection.GeneratedProtocolMessageType('CeresScanMatcherOptions3D', (_message.Message,), {
  'DESCRIPTOR' : _CERESSCANMATCHEROPTIONS3D,
  '__module__' : 'cartographer.mapping.proto.scan_matching.ceres_scan_matcher_options_3d_pb2'
  # @@protoc_insertion_point(class_scope:cartographer.mapping.scan_matching.proto.CeresScanMatcherOptions3D)
  })
_sym_db.RegisterMessage(CeresScanMatcherOptions3D)


# @@protoc_insertion_point(module_scope)
