# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cartographer/mapping/proto/scan_matching/ceres_scan_matcher_options_2d.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cartographer.common.proto import ceres_solver_options_pb2 as cartographer_dot_common_dot_proto_dot_ceres__solver__options__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='cartographer/mapping/proto/scan_matching/ceres_scan_matcher_options_2d.proto',
  package='cartographer.mapping.scan_matching.proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\nLcartographer/mapping/proto/scan_matching/ceres_scan_matcher_options_2d.proto\x12(cartographer.mapping.scan_matching.proto\x1a\x34\x63\x61rtographer/common/proto/ceres_solver_options.proto\"\xbc\x01\n\x19\x43\x65resScanMatcherOptions2D\x12\x1d\n\x15occupied_space_weight\x18\x01 \x01(\x01\x12\x1a\n\x12translation_weight\x18\x02 \x01(\x01\x12\x17\n\x0frotation_weight\x18\x03 \x01(\x01\x12K\n\x14\x63\x65res_solver_options\x18\t \x01(\x0b\x32-.cartographer.common.proto.CeresSolverOptionsb\x06proto3'
  ,
  dependencies=[cartographer_dot_common_dot_proto_dot_ceres__solver__options__pb2.DESCRIPTOR,])




_CERESSCANMATCHEROPTIONS2D = _descriptor.Descriptor(
  name='CeresScanMatcherOptions2D',
  full_name='cartographer.mapping.scan_matching.proto.CeresScanMatcherOptions2D',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='occupied_space_weight', full_name='cartographer.mapping.scan_matching.proto.CeresScanMatcherOptions2D.occupied_space_weight', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='translation_weight', full_name='cartographer.mapping.scan_matching.proto.CeresScanMatcherOptions2D.translation_weight', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rotation_weight', full_name='cartographer.mapping.scan_matching.proto.CeresScanMatcherOptions2D.rotation_weight', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ceres_solver_options', full_name='cartographer.mapping.scan_matching.proto.CeresScanMatcherOptions2D.ceres_solver_options', index=3,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=177,
  serialized_end=365,
)

_CERESSCANMATCHEROPTIONS2D.fields_by_name['ceres_solver_options'].message_type = cartographer_dot_common_dot_proto_dot_ceres__solver__options__pb2._CERESSOLVEROPTIONS
DESCRIPTOR.message_types_by_name['CeresScanMatcherOptions2D'] = _CERESSCANMATCHEROPTIONS2D
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CeresScanMatcherOptions2D = _reflection.GeneratedProtocolMessageType('CeresScanMatcherOptions2D', (_message.Message,), {
  'DESCRIPTOR' : _CERESSCANMATCHEROPTIONS2D,
  '__module__' : 'cartographer.mapping.proto.scan_matching.ceres_scan_matcher_options_2d_pb2'
  # @@protoc_insertion_point(class_scope:cartographer.mapping.scan_matching.proto.CeresScanMatcherOptions2D)
  })
_sym_db.RegisterMessage(CeresScanMatcherOptions2D)


# @@protoc_insertion_point(module_scope)
