# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cartographer/mapping/proto/scan_matching/fast_correlative_scan_matcher_options_3d.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cartographer/mapping/proto/scan_matching/fast_correlative_scan_matcher_options_3d.proto',
  package='cartographer.mapping.scan_matching.proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\nWcartographer/mapping/proto/scan_matching/fast_correlative_scan_matcher_options_3d.proto\x12(cartographer.mapping.scan_matching.proto\"\x84\x02\n#FastCorrelativeScanMatcherOptions3D\x12\x1e\n\x16\x62ranch_and_bound_depth\x18\x02 \x01(\x05\x12\x1d\n\x15\x66ull_resolution_depth\x18\x08 \x01(\x05\x12\x1c\n\x14min_rotational_score\x18\x04 \x01(\x01\x12 \n\x18min_low_resolution_score\x18\t \x01(\x01\x12\x1f\n\x17linear_xy_search_window\x18\x05 \x01(\x01\x12\x1e\n\x16linear_z_search_window\x18\x06 \x01(\x01\x12\x1d\n\x15\x61ngular_search_window\x18\x07 \x01(\x01\x62\x06proto3'
)




_FASTCORRELATIVESCANMATCHEROPTIONS3D = _descriptor.Descriptor(
  name='FastCorrelativeScanMatcherOptions3D',
  full_name='cartographer.mapping.scan_matching.proto.FastCorrelativeScanMatcherOptions3D',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='branch_and_bound_depth', full_name='cartographer.mapping.scan_matching.proto.FastCorrelativeScanMatcherOptions3D.branch_and_bound_depth', index=0,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='full_resolution_depth', full_name='cartographer.mapping.scan_matching.proto.FastCorrelativeScanMatcherOptions3D.full_resolution_depth', index=1,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='min_rotational_score', full_name='cartographer.mapping.scan_matching.proto.FastCorrelativeScanMatcherOptions3D.min_rotational_score', index=2,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='min_low_resolution_score', full_name='cartographer.mapping.scan_matching.proto.FastCorrelativeScanMatcherOptions3D.min_low_resolution_score', index=3,
      number=9, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='linear_xy_search_window', full_name='cartographer.mapping.scan_matching.proto.FastCorrelativeScanMatcherOptions3D.linear_xy_search_window', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='linear_z_search_window', full_name='cartographer.mapping.scan_matching.proto.FastCorrelativeScanMatcherOptions3D.linear_z_search_window', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='angular_search_window', full_name='cartographer.mapping.scan_matching.proto.FastCorrelativeScanMatcherOptions3D.angular_search_window', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=134,
  serialized_end=394,
)

DESCRIPTOR.message_types_by_name['FastCorrelativeScanMatcherOptions3D'] = _FASTCORRELATIVESCANMATCHEROPTIONS3D
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FastCorrelativeScanMatcherOptions3D = _reflection.GeneratedProtocolMessageType('FastCorrelativeScanMatcherOptions3D', (_message.Message,), {
  'DESCRIPTOR' : _FASTCORRELATIVESCANMATCHEROPTIONS3D,
  '__module__' : 'cartographer.mapping.proto.scan_matching.fast_correlative_scan_matcher_options_3d_pb2'
  # @@protoc_insertion_point(class_scope:cartographer.mapping.scan_matching.proto.FastCorrelativeScanMatcherOptions3D)
  })
_sym_db.RegisterMessage(FastCorrelativeScanMatcherOptions3D)


# @@protoc_insertion_point(module_scope)
