# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cartographer/mapping/proto/scan_matching/fast_correlative_scan_matcher_options_2d.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cartographer/mapping/proto/scan_matching/fast_correlative_scan_matcher_options_2d.proto',
  package='cartographer.mapping.scan_matching.proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\nWcartographer/mapping/proto/scan_matching/fast_correlative_scan_matcher_options_2d.proto\x12(cartographer.mapping.scan_matching.proto\"\x82\x01\n#FastCorrelativeScanMatcherOptions2D\x12\x1c\n\x14linear_search_window\x18\x03 \x01(\x01\x12\x1d\n\x15\x61ngular_search_window\x18\x04 \x01(\x01\x12\x1e\n\x16\x62ranch_and_bound_depth\x18\x02 \x01(\x05\x62\x06proto3'
)




_FASTCORRELATIVESCANMATCHEROPTIONS2D = _descriptor.Descriptor(
  name='FastCorrelativeScanMatcherOptions2D',
  full_name='cartographer.mapping.scan_matching.proto.FastCorrelativeScanMatcherOptions2D',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='linear_search_window', full_name='cartographer.mapping.scan_matching.proto.FastCorrelativeScanMatcherOptions2D.linear_search_window', index=0,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='angular_search_window', full_name='cartographer.mapping.scan_matching.proto.FastCorrelativeScanMatcherOptions2D.angular_search_window', index=1,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='branch_and_bound_depth', full_name='cartographer.mapping.scan_matching.proto.FastCorrelativeScanMatcherOptions2D.branch_and_bound_depth', index=2,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=134,
  serialized_end=264,
)

DESCRIPTOR.message_types_by_name['FastCorrelativeScanMatcherOptions2D'] = _FASTCORRELATIVESCANMATCHEROPTIONS2D
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FastCorrelativeScanMatcherOptions2D = _reflection.GeneratedProtocolMessageType('FastCorrelativeScanMatcherOptions2D', (_message.Message,), {
  'DESCRIPTOR' : _FASTCORRELATIVESCANMATCHEROPTIONS2D,
  '__module__' : 'cartographer.mapping.proto.scan_matching.fast_correlative_scan_matcher_options_2d_pb2'
  # @@protoc_insertion_point(class_scope:cartographer.mapping.scan_matching.proto.FastCorrelativeScanMatcherOptions2D)
  })
_sym_db.RegisterMessage(FastCorrelativeScanMatcherOptions2D)


# @@protoc_insertion_point(module_scope)
