# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cartographer/mapping/proto/scan_matching/real_time_correlative_scan_matcher_options.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cartographer/mapping/proto/scan_matching/real_time_correlative_scan_matcher_options.proto',
  package='cartographer.mapping.scan_matching.proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\nYcartographer/mapping/proto/scan_matching/real_time_correlative_scan_matcher_options.proto\x12(cartographer.mapping.scan_matching.proto\"\xaf\x01\n%RealTimeCorrelativeScanMatcherOptions\x12\x1c\n\x14linear_search_window\x18\x01 \x01(\x01\x12\x1d\n\x15\x61ngular_search_window\x18\x02 \x01(\x01\x12%\n\x1dtranslation_delta_cost_weight\x18\x03 \x01(\x01\x12\"\n\x1arotation_delta_cost_weight\x18\x04 \x01(\x01\x62\x06proto3'
)




_REALTIMECORRELATIVESCANMATCHEROPTIONS = _descriptor.Descriptor(
  name='RealTimeCorrelativeScanMatcherOptions',
  full_name='cartographer.mapping.scan_matching.proto.RealTimeCorrelativeScanMatcherOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='linear_search_window', full_name='cartographer.mapping.scan_matching.proto.RealTimeCorrelativeScanMatcherOptions.linear_search_window', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='angular_search_window', full_name='cartographer.mapping.scan_matching.proto.RealTimeCorrelativeScanMatcherOptions.angular_search_window', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='translation_delta_cost_weight', full_name='cartographer.mapping.scan_matching.proto.RealTimeCorrelativeScanMatcherOptions.translation_delta_cost_weight', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rotation_delta_cost_weight', full_name='cartographer.mapping.scan_matching.proto.RealTimeCorrelativeScanMatcherOptions.rotation_delta_cost_weight', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=136,
  serialized_end=311,
)

DESCRIPTOR.message_types_by_name['RealTimeCorrelativeScanMatcherOptions'] = _REALTIMECORRELATIVESCANMATCHEROPTIONS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RealTimeCorrelativeScanMatcherOptions = _reflection.GeneratedProtocolMessageType('RealTimeCorrelativeScanMatcherOptions', (_message.Message,), {
  'DESCRIPTOR' : _REALTIMECORRELATIVESCANMATCHEROPTIONS,
  '__module__' : 'cartographer.mapping.proto.scan_matching.real_time_correlative_scan_matcher_options_pb2'
  # @@protoc_insertion_point(class_scope:cartographer.mapping.scan_matching.proto.RealTimeCorrelativeScanMatcherOptions)
  })
_sym_db.RegisterMessage(RealTimeCorrelativeScanMatcherOptions)


# @@protoc_insertion_point(module_scope)
