# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cartographer/cloud/proto/map_builder_server_options.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cartographer.mapping.proto import map_builder_options_pb2 as cartographer_dot_mapping_dot_proto_dot_map__builder__options__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='cartographer/cloud/proto/map_builder_server_options.proto',
  package='cartographer.cloud.proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n9cartographer/cloud/proto/map_builder_server_options.proto\x12\x18\x63\x61rtographer.cloud.proto\x1a\x34\x63\x61rtographer/mapping/proto/map_builder_options.proto\"\xa7\x02\n\x17MapBuilderServerOptions\x12\x16\n\x0eserver_address\x18\x01 \x01(\t\x12\x18\n\x10num_grpc_threads\x18\x02 \x01(\x05\x12\x19\n\x11num_event_threads\x18\x03 \x01(\x05\x12J\n\x13map_builder_options\x18\x04 \x01(\x0b\x32-.cartographer.mapping.proto.MapBuilderOptions\x12\x1d\n\x15uplink_server_address\x18\x05 \x01(\t\x12\x19\n\x11upload_batch_size\x18\x06 \x01(\x05\x12\x1d\n\x15\x65nable_ssl_encryption\x18\x07 \x01(\x08\x12\x1a\n\x12\x65nable_google_auth\x18\t \x01(\x08\x62\x06proto3'
  ,
  dependencies=[cartographer_dot_mapping_dot_proto_dot_map__builder__options__pb2.DESCRIPTOR,])




_MAPBUILDERSERVEROPTIONS = _descriptor.Descriptor(
  name='MapBuilderServerOptions',
  full_name='cartographer.cloud.proto.MapBuilderServerOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='server_address', full_name='cartographer.cloud.proto.MapBuilderServerOptions.server_address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_grpc_threads', full_name='cartographer.cloud.proto.MapBuilderServerOptions.num_grpc_threads', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_event_threads', full_name='cartographer.cloud.proto.MapBuilderServerOptions.num_event_threads', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='map_builder_options', full_name='cartographer.cloud.proto.MapBuilderServerOptions.map_builder_options', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='uplink_server_address', full_name='cartographer.cloud.proto.MapBuilderServerOptions.uplink_server_address', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='upload_batch_size', full_name='cartographer.cloud.proto.MapBuilderServerOptions.upload_batch_size', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='enable_ssl_encryption', full_name='cartographer.cloud.proto.MapBuilderServerOptions.enable_ssl_encryption', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='enable_google_auth', full_name='cartographer.cloud.proto.MapBuilderServerOptions.enable_google_auth', index=7,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=142,
  serialized_end=437,
)

_MAPBUILDERSERVEROPTIONS.fields_by_name['map_builder_options'].message_type = cartographer_dot_mapping_dot_proto_dot_map__builder__options__pb2._MAPBUILDEROPTIONS
DESCRIPTOR.message_types_by_name['MapBuilderServerOptions'] = _MAPBUILDERSERVEROPTIONS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MapBuilderServerOptions = _reflection.GeneratedProtocolMessageType('MapBuilderServerOptions', (_message.Message,), {
  'DESCRIPTOR' : _MAPBUILDERSERVEROPTIONS,
  '__module__' : 'cartographer.cloud.proto.map_builder_server_options_pb2'
  # @@protoc_insertion_point(class_scope:cartographer.cloud.proto.MapBuilderServerOptions)
  })
_sym_db.RegisterMessage(MapBuilderServerOptions)


# @@protoc_insertion_point(module_scope)
